[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    -s
    --html=reports/report_IntegrationWorkflows.html
    --self-contained-html
    --tb=short
    --log-cli-level=INFO
    --log-file-level=INFO
    --log-file=reports/test_logs.log
markers =
    workflow1
    workflow2
    workflow3